chatApp/urls.py
from django.contrib import admin
from django.urls import path, include
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from users import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
    path('api-auth/', include('rest_framework.urls')),
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='user_profile'),
    path('', include('chatMe.urls')),
    path('logout/', auth_views.LogoutView.as_view(template_name='user_logout.html'), name='user_logout')
]

if settings.DEBUG:
         urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chatMe/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('home/', views.home, name='home'),
    path('chat/', views.chat_view, name='chats'),
    path('chat/<int:sender>/<int:receiver>/', views.message_view, name='chat'),
    path('api/messages/<int:sender>/<int:receiver>/', views.my_message, name='message-detail'),
    path('api/messages/', views.my_message, name='message-list'),
]

chatMe/models.py
from django.db import models
from django.contrib.auth.models import User

class Message(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sender')
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name='receiver')
    message = models.CharField(max_length=1200)
    timestamp = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False)

    def __str__(self):
        return self.message

    class Meta:
        ordering = ('timestamp',)

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.files.storage import default_storage as storage
from PIL import Image


class Profile(models.Model):
     user = models.OneToOneField(User, on_delete=models.CASCADE)
     image = models.ImageField(default='avatar.png', upload_to='profile_pics')

     def __str__(self):
         return f'{self.user.username} Profile'

     def save(self, *args, **kwargs):
         if not self.user.username:
             return

         super(Profile, self).save()
         if self.image:
             size = 200, 200
             image = Image.open(self.image)
             image.thumbnail(size, Image.ANTIALIAS)
             fh = storage.open(self.image.name, "w")
             format = 'png'
             image.save(fh, format)
             fh.close()

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile

class UserForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = [
            'username',
            'email',
        ]


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = [
            'username',
            'email',
        ]


class ProfileUpdateForm(forms.ModelForm):
      class Meta:
           model = Profile
           fields = ['image']

chatMe/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.http.response import JsonResponse, HttpResponse
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt
from rest_framework.parsers import JSONParser
from .models import Message
from .serializers import MessageSerializer

def home(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if request.user.is_authenticated:
            return redirect('chats')
        if user is not None:
            login(request, user)
        else:
            return HttpResponse('{"error": "User does not exist"}')
        return redirect('chats')
    return render(request, 'home_index.html', {})


@csrf_exempt
def my_message(request, sender=None, receiver=None):
    if request.method == 'GET':
        messages = Message.objects.filter(sender_id=sender, receiver_id=receiver, is_read=False)
        serializer = MessageSerializer(messages, many=True, context={'request': request})
        for message in messages:
            message.is_read = True
            message.save()
        return JsonResponse(serializer.data, safe=False)

    elif request.method == 'POST':
        data = JSONParser().parse(request)
        serializer = MessageSerializer(data=data)
        if serializer.is_valid():
            serializer.save()
            return JsonResponse(serializer.data, status=201)
        return JsonResponse(serializer.errors, status=400)

def chat_view(request):
    if not request.user.is_authenticated:
        return redirect('home')
    if request.method == "GET":
        return render(request, 'chat_view.html',
                      {'users': User.objects.exclude(username=request.user.username)})


def message_view(request, sender, receiver):
    if not request.user.is_authenticated:
        return redirect('home')
    if request.method == "GET":
        return render(request, "messageMe.html",
                      {'users': User.objects.exclude(username=request.user.username),
                       'receiver': User.objects.get(id=receiver),
                       'anime': Message.objects.filter(sender_id=sender, receiver_id=receiver) |
                                   Message.objects.filter(sender_id=receiver, receiver_id=sender)})

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from .forms import UserForm, ProfileUpdateForm, UserUpdateForm
from .models import Profile


def register(request):
    form = UserCreationForm()
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f"Your account has been created! You are now able to log in")
            return redirect('home')
    else:
        form = UserForm()
    context = {
        'form': form
    }
    return render(request, 'user_register.html', context)


def profile(request):
    try:
        profile = request.user.profile
    except:
        profile = Profile(user=request.user)
    if request.method == "POST":
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST,
                                   request.FILES,
                                   instance=profile)
        if u_form.is_valid() and p_form.is_valid():
           u_form.save()
           p_form.save()
           messages.success(request, f"Your account has been Updated!")
           return redirect('user_profile')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=profile)

    context = {
        'u_form': u_form,
        'p_form': p_form
    }

    return render(request, 'user_profile.html', context)

chatMe/templates/alert.html
{% if messages %}
    {% for mess in messages %}
        <div id="mess" class="container">
            <div class="alert alert-{{  mess.tags }} alert-dismissable text-center" role="alert">
                <button type="button" class="close" data-dismiss="alert">
                    <span aria-hidden="true"></span>
                </button>
                <strong>
                    {% if mess.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                        Error:
                    {% else %}
                        {{ mess.tags|title }}
                    {% endif %}
                </strong>
                {{ mess }}
            </div>
        </div>
    {% endfor %}
{% endif %}

chatMe/templates/alertM.html
{% if messages %}
       {% for mess in messages %}
               <div class="alert-success alert">{{ mess }}</div>
       {% endfor %}
{% endif %}

chatMe/templates/chat_view.html
{% extends 'home_index.html' %}
{% load static %}
{% block body %}
<nav class="lighten-3" style="background-color: gray">
    <div class="nav-wrapper container">
      <a href="#" class="brand-logo">Chat</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li><a href="">{{ request.user.username }}</a></li>
          <li><a href="{% url 'user_profile' %}">Profile</a></li>
          <li><a href="{% url 'user_logout' %}"><i class="material-icons">power_settings_new</i></a></li>
      </ul>
    </div>
</nav>
    <div class="section" style="height: 80vh">
    <div class="row">
        <div class="col s3 no">
            <div class="simple">
                <div class="collection">
                    {% for user in users %}
                    <a href="{% url 'chat' request.user.id user.id %}" id="user{{ user.id }}" class="collection-item row">
                        {% if user.profile.image %}
                            <img  style="border-radius: 50%; height: 70px;" src="{{ user.profile.image.url }}" class="col s4">
                        {% else %}
                            <img style="border-radius: 50%; height: 70px;" src="{% static 'media/avatar.png' %}" class="col s4">
                        {% endif %}
                        <div class="col s8">
                         <span class="title" style="font-weight: bolder; position: relative; right: 5%;"> {{ user.username }}</span>
                        </div>
                    </a>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="col s9 yes">
            <div class="card">
            <div id="board" class="section grey lighten-3" style="height: 68vh; padding: 5px; overflow-y: scroll;">
                {% block messages %}

                {% endblock %}
            </div>
            <form id="chat-box" class="form-group {% block hide %}hide{% endblock %}" method="post">
                {% csrf_token %}
                <div class="row">
                    <div class="col s11">
                        <div class="input-field">
                            <input id="id_message" name="message" type="text" placeholder="Type your message..">
                        </div>
                    </div>
                    <div class="col s1" style="line-height: 80px">
                        <button class="btn btn-floating lighten-2 waves-effect waves-light"
                                style="background-color: gray; position: relative; right: 20%;"><i class="material-icons">send</i></button>
                    </div>
                </div>
            </form>
            </div>
        </div>
    </div>
    </div>
    <script src="{% static 'js/chat.js' %}"></script>
    <script>
        // For receiving
        sender_id = "{{ receiver.id }}";
        receiver_id = "{{ request.user.id }}";

        //For sending
        $(function () {
            scrolltoend();
            $('#chat-box').on('submit', function (event) {
                event.preventDefault();
                var message = $('#id_message');
                send('{{ request.user.username }}', '{{ receiver.username }}', message.val());
                message.val('');
            })
        })
    </script>
{% endblock %}

chatMe/templates/home_index.html
{% load static %}
  <!DOCTYPE html>
  <html>
    <head>
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link type="text/css" rel="stylesheet" href="{% static 'css/materialize.min.css' %}"  media="screen,projection"/>
        <link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}"  media="screen,projection"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
        <script type="text/javascript" src="{% static 'js/materialize.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/chat.js' %}"></script>
    </head>

    <body>
    <div class="section gray lighten-3" style="background-color: gray;">
            <div class="container white-text center-align text">
              <h2>A Simple Chat Application</h2>
            </div>
    </div>
    {% include 'alertM.html' %}
    {% block body %}
        {% include 'main.html' %}
    {% endblock %}
    </body>

  </html>

chatMe/templates/main.html
        <div class="container">
            <div class="row">
            <div class="col s12 m8 l6 offset-m2 offset-l3">
                <div class="section center-block">
                <div>
                    {% block form %}
                    <h4>Login</h4>
                    <form id="login-form" class="form-group" method="post">{% csrf_token %}
                        <div class="col-md-6 input-col">
                             <div>
                                <label>username</label>
                                <input data-val="true" data-val-required="required" id="id_username" name="username" type="text" value="">
                                <span class="field-validation-valid text-danger" data-valmsg-replace="true"></span>
                             </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6 input-col" style="position: relative; left: 2%; width: 96%;">
                                <label>password</label>
                                <input data-val="true" data-val-required="required" id="id_password" name="password" type="password">
                                <span class="field-validation-valid text-danger" data-valmsg-replace="true"></span>
                            </div>
                        </div>
                         <div class="row">
                            <div class="col s8">
                                <a href="{% url 'register' %}" style="color: gray">Register</a>
                            </div>
                            <div class="col s4">
                                <div class="right">
                                    <button class="btn waves-effect waves-light pull-s12" style="background-color: gray">Login</button>
                                </div>
                            </div>
                        </div>
                    </form>
                    {% endblock %}
                </div>
            </div>
            </div>
            </div>
        </div>

chatMe/templates/messageMe.html
{% extends 'chat_view.html' %}
{% block hide %}{% endblock %}
{% block messages %}
    {% for naruto in anime %}
        {% if naruto.sender == request.user %}
              <div class="card-panel right" style="width: 75%; position: relative">
                 <div style="position: absolute; top: 0; left:3px; font-weight: bolder" class="title">You</div>{{ naruto }}
              </div>
        {% else %}
           <div class="card-panel left blue lighten-5" style="width: 75%; position: relative">
              <div style="position: absolute; top: 0; left:3px; font-weight: bolder" class="title">{{ naruto.sender }}</div>{{ naruto }}
           </div>
        {% endif %}
    {% endfor %}
<script>
$(function () {
    $('#user{{ receiver.id }}').addClass('active');
    //Call receive function each 1 seconds to check for new messages in the database
    setInterval(receive,1000)
})
</script>
{% endblock %}

chatMe/templates/my_base.html
{% load static %}
  <!DOCTYPE html>
  <html>
    <head>
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link type="text/css" rel="stylesheet" href="{% static 'css/materialize.min.css' %}"  media="screen,projection"/>
        <link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}"  media="screen,projection"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />
        <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
         <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.15.4/css/fontawesome.min.css">
       <link rel="preconnect" href="https://fonts.gstatic.com">
       <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css"/>
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    </head>

    <body>
    <div class="section gray lighten-3" style="background-color: gray;">
            <div class="container white-text center-align text">
              <h2>A Simple Chat Application</h2>
            </div>
    </div>
     {% include 'alert.html' %}
      <br>
       {% block name %}
       {% endblock %}
    </body>

  </html>

chatMe/templates/user_logout.html
{% extends "my_base.html" %}
{% block name %}
<body style="background-color: white;">
  <h1 style="margin-bottom: 3%;"></h1>
  <div class="both-log" style="max-width: 600px; width: 80%;
           margin: 0 auto; font-family: 'Ubuntu', sans-serif; font-size: 1rem;">
          <h3>You have been logged out</h3>
          <div >
               <a class="btn btn-outline-secondary" href="{% url 'home' %}">Login</a>
          </div>
  </div>
</body>
{% endblock %}

chatMe/templates/user_profile.html
{% extends "my_base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block name %}
<body style="background-color: white;">
 <div class="image-body">
     <a class="btn btn-secondary" href="{% url 'chats' %}" id="back"><i class="fas fa-chevron-left"></i></a>
     <h1 style="margin-bottom: 2%;"></h1>
   <div class="image-head">
       {% if user.profile.image %}
           <img src="{{ user.profile.image.url }}">
       {% else %}
          <img  src="{% static 'media/default.jpg' %}">
       {% endif %}
        <div class="heady">
         <h2><i class="fa fa-user" aria-hidden="true"> {{ user.username }} </i></h2>
        <p><i class="fa fa-envelope" aria-hidden="true"> {{ user.email }} </i></p>
        </div>
   </div>
   <form action="." method="POST" enctype="multipart/form-data">{% csrf_token %}
         <div class="income">
             <br>
                {{u_form|crispy}}
                {{p_form|crispy}}
             <br>
             <div><button class="btn btn-secondary" type="submit">Update</button></div>
         </div>
   </form>
 </div>
</body>
{% endblock %}

chatMe/templates/user_register.html
{% extends "my_base.html" %}
{% load crispy_forms_tags %}

{% block name %}
<body style="background: #fff;">
   <div class="both">
     <h1 style="margin-bottom: 3%;"></h1>
    <form action="." method="POST">{% csrf_token %}
         <fieldset class="field">
             <div class="create">CREATE ACCOUNT</div>
             <br>
           {{ form|crispy }}
             <br>
           <div>
             <input type="submit" value="sign up">
           </div>
          <div>
              <small>Already Have an Account? <a href="{% url 'home' %}" style="text-decoration: none;">
                  Sign In</a></small>
          </div>
         </fieldset>
    </form>
  </div>
</body>
{% endblock %}